#include "serialization.h"
#include "bytecode.h"
#include "caosVar.h"
#include "caosScript.h"

BOOST_CLASS_EXPORT(caosOp)
BOOST_CLASS_EXPORT(caosNoop)
BOOST_CLASS_EXPORT(caosJMP)
BOOST_CLASS_EXPORT(simpleCaosOp)
BOOST_CLASS_EXPORT(caosREPS)
BOOST_CLASS_EXPORT(caosGSUB)
BOOST_CLASS_EXPORT(caosCond)
BOOST_CLASS_EXPORT(caosENUM_POP)
BOOST_CLASS_EXPORT(caosSTOP)
BOOST_CLASS_EXPORT(caosAssert)
BOOST_CLASS_EXPORT(ConstOp)
BOOST_CLASS_EXPORT(opVAxx)
BOOST_CLASS_EXPORT(opOVxx)
BOOST_CLASS_EXPORT(opMVxx)
BOOST_CLASS_EXPORT(opBytestr)
BOOST_CLASS_EXPORT(script)
BOOST_CLASS_EXPORT(caosScript)
BOOST_CLASS_EXPORT(caosVar)
